# Generated by Django 3.1.2 on 2020-10-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotinfo',
            name='interval',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plotinfo',
            name='step',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plotinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
