# Generated by Django 3.1.2 on 2020-10-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201027_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotinfo',
            name='fun',
            field=models.CharField(help_text='Введите вашу функцию', max_length=50),
        ),
        migrations.AlterField(
            model_name='plotinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plotinfo',
            name='interval',
            field=models.IntegerField(help_text='Интервал времени в днях'),
        ),
        migrations.AlterField(
            model_name='plotinfo',
            name='step',
            field=models.IntegerField(help_text='Шаг моделирования в часах'),
        ),
    ]
