# Generated by Django 3.1.2 on 2020-10-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201027_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotinfo',
            name='graph',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
