# Generated by Django 3.1.2 on 2020-10-28 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201027_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotinfo',
            name='actualdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 8, 1, 26, 506458)),
        ),
    ]
